import '@/styles/globals.css';
import Navbar from "@/components/Navbar/Navbar"
import { SelectedPage } from "@/types/types"

type Props = {
  selectPage: string;
  setSelectedPage: (value: string) => void;
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
